server:
  port: 8080 #服务器端口号

#日志
logging:
  level: #自定义框架日志级别
    org.springframework: warn
    com.example: debug

spring:
  datasource:
    url: jdbc:mysql://192.168.153.133:3300/score_manager?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=UTF-8
    #url: jdbc:mysql:///score_manager?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource #连接池类型
    hikari:
      minimum-idle: 5
      # 空闲连接存活最大时间，默认600000（10分钟）
      idle-timeout: 5000
      # 连接池最大连接数，默认是10
      maximum-pool-size: 10
      # 此属性控制从池返回的连接的默认自动提交行为,默认值：true
      auto-commit: true
      # 连接池名称
      pool-name: DateSourceHikariCP
      # 此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟
      max-lifetime: 1800000
      # 数据库连接超时时间,默认30秒，即30000
      connection-timeout: 30000
  mail: #邮箱配置
    host: smtp.qq.com
    username: 362387242@qq.com
    password: dccrzwcufxygbjhh
    port: 587
    default-encoding: utf-8
    properties:
      mail:
        smtp:
          timeout: 5000
          auth: true
          starttls:
            enable: true
            required: true

#Mybatis配置
mybatis:
  type-aliases-package: com.example.entity #别名
  mapper-locations: classpath*:/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true #支持驼峰与下划线之间的转化

#分页配置
pagehelper:
  helper-dialect: mysql #指定数据库
  reasonable: true #分页合理化，最大最小页时不溢出
  support-methods-arguments: false #是否自动分页
  params: count=countSql


